apiVersion: v1
kind: Service
metadata:
  name: kubernetes-multipod
  labels:
    app: kubernetes-multipod
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: kubernetes-multipod
  type: NodePort
